# Generated by Django 4.0.5 on 2024-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
